env:
  es2021: true
  node: true
  jest: true
extends:
  - google
  - 'eslint:recommended'
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules: 
  camelcase: 'off'
  max-len: 'off'
  prefer-rest-params: 'off'
  arrow-parens: 'off'