version: '3.7'

services:
  rocky:
    build:
      context: .
    ports:
      - 48000:48000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # healthcheck:
    #   test: curl --fail http://localhost:48000/api/healthcheck || exit 1
    #   interval: 30s
    #   retries: 3
    #   start_period: 20s
    #   timeout: 5s