version: '3.7'

services:
  rocky:
    build:
      context: .
    ports:
      - 8888:8888
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: curl --fail http://localhost:8888/api/healthcheck || exit 1
      interval: 30s
      retries: 3
      start_period: 20s
      timeout: 5s